# Working with Text Data and Naive Bayes in scikit-learn

## Agenda

**Working with text data**

- Representing text as data
- Reading SMS data
- Vectorizing SMS data
- Examining the tokens and their counts
- Bonus: Calculating the "spamminess" of each token

**Naive Bayes classification**

- Building a Naive Bayes model
- Comparing Naive Bayes with logistic regression

## Part 1: Representing text as data

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> Text Analysis is a major application field for machine learning algorithms. However the raw data, a sequence of symbols cannot be fed directly to the algorithms themselves as most of them expect **numerical feature vectors with a fixed size** rather than the **raw text documents with variable length**.

We will use [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) to "convert text into a matrix of token counts":

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
# start with a simple example
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [3]:
simple_train

['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [7]:
# learn the 'vocabulary' of the training data
vect = CountVectorizer()
vect.fit(simple_train)
vect.get_feature_names()

[u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [8]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [9]:
# print the sparse matrix
print simple_train_dtm

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [10]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

Text
0           call you tonight
1              Call me a cab
2  please call me... PLEASE!

In [14]:
# examine the vocabulary and document-term matrix together
import pandas as pd
pd.concat([pd.DataFrame(simple_train, columns=['Text']),
           pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())],
         axis=1)


Text  cab  call  me  please  tonight  you
0           call you tonight    0     1   0       0        1    1
1              Call me a cab    1     1   1       0        0    0
2  please call me... PLEASE!    0     1   1       2        0    0

In [ ]:
n-grams

"The sky is so blue today"

2-grams

The The_sky sky sky_is is is_so so so_blue blue blue_today today

3-grams

The The_sky The_sky_is
Sky Sky_is sky_is_so

n-grams

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> In this scheme, features and samples are defined as follows:

> - Each individual token occurrence frequency (normalized or not) is treated as a **feature**.
> - The vector of all the token frequencies for a given document is considered a multivariate **sample**.

> A **corpus of documents** can thus be represented by a matrix with **one row per document** and **one column per token** (e.g. word) occurring in the corpus.

> We call **vectorization** the general process of turning a collection of text documents into numerical feature vectors. This specific strategy (tokenization, counting and normalization) is called the **Bag of Words** or "Bag of n-grams" representation. Documents are described by word occurrences while completely ignoring the relative position information of the words in the document.

In [15]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test = ["please don't call me"]
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [16]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

**Summary:**

- `vect.fit(train)` learns the vocabulary of the training data
- `vect.transform(train)` uses the fitted vocabulary to build a document-term matrix from the training data
- `vect.transform(test)` uses the fitted vocabulary to build a document-term matrix from the testing data (and ignores tokens it hasn't seen before)

## Part 2: Reading SMS data

In [17]:
# read tab-separated file
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/sms.tsv'
col_names = ['label', 'message']
sms = pd.read_table(url, sep='\t', header=None, names=col_names)
print sms.shape

(5572, 2)


In [20]:
sms.query("label == 'spam'")[:20]

label                                            message
2    spam  Free entry in 2 a wkly comp to win FA Cup fina...
5    spam  FreeMsg Hey there darling it's been 3 week's n...
8    spam  WINNER!! As a valued network customer you have...
9    spam  Had your mobile 11 months or more? U R entitle...
11   spam  SIX chances to win CASH! From 100 to 20,000 po...
12   spam  URGENT! You have won a 1 week FREE membership ...
15   spam  XXXMobileMovieClub: To use your credit, click ...
19   spam  England v Macedonia - dont miss the goals/team...
34   spam  Thanks for your subscription to Ringtone UK yo...
42   spam  07732584351 - Rodger Burns - MSG = We tried to...
54   spam  SMS. ac Sptv: The New Jersey Devils and the De...
56   spam  Congrats! 1 year special cinema pass for 2 is ...
65   spam  As a valued customer, I am pleased to advise y...
67   spam  Urgent UR awarded a complimentary trip to Euro...
68   spam  Did you hear about the new "Divorce Barbie"? I...
93   spam  Please call our customer service representativ...
95   spam  Your free ringtone is waiting to be collected....
114  spam  GENT! We are trying to contact you. Last weeke...
117  spam  You are a winner U have been specially selecte...
120  spam  PRIVATE! Your 2004 Account Statement for 07742...

In [21]:
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [22]:
# convert label to a numeric variable
sms['label'] = sms.label.map({'ham':0, 'spam':1})

In [23]:
# define X and y
X = sms.message
y = sms.label

In [25]:
# split into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print X_train.shape
print X_test.shape

(4179,)
(1393,)


## Part 3: Vectorizing SMS data

In [26]:
# instantiate the vectorizer
vect = CountVectorizer()

In [27]:
# learn training data vocabulary, then create document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [28]:
# alternative: combine fit and transform into a single step
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [29]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

## Part 4: Examining the tokens and their counts

In [30]:
# store token names
X_train_tokens = vect.get_feature_names()

In [31]:
# first 50 tokens
print X_train_tokens[:50]

[u'00', u'000', u'008704050406', u'0121', u'01223585236', u'01223585334', u'0125698789', u'02', u'0207', u'02072069400', u'02073162414', u'02085076972', u'021', u'03', u'04', u'0430', u'05', u'050703', u'0578', u'06', u'07', u'07008009200', u'07090201529', u'07090298926', u'07123456789', u'07732584351', u'07734396839', u'07742676969', u'0776xxxxxxx', u'07781482378', u'07786200117', u'078', u'07801543489', u'07808', u'07808247860', u'07808726822', u'07815296484', u'07821230901', u'07880867867', u'0789xxxxxxx', u'07946746291', u'0796xxxxxx', u'07973788240', u'07xxxxxxxxx', u'08', u'0800', u'08000407165', u'08000776320', u'08000839402', u'08000930705']


In [32]:
# last 50 tokens
print X_train_tokens[-50:]

[u'yer', u'yes', u'yest', u'yesterday', u'yet', u'yetunde', u'yijue', u'ym', u'ymca', u'yo', u'yoga', u'yogasana', u'yor', u'yorge', u'you', u'youdoing', u'youi', u'youphone', u'your', u'youre', u'yourjob', u'yours', u'yourself', u'youwanna', u'yowifes', u'yoyyooo', u'yr', u'yrs', u'ything', u'yummmm', u'yummy', u'yun', u'yunny', u'yuo', u'yuou', u'yup', u'zac', u'zaher', u'zealand', u'zebra', u'zed', u'zeros', u'zhong', u'zindgi', u'zoe', u'zoom', u'zouk', u'zyada', u'\xe8n', u'\u3028ud']


In [33]:
# view X_train_dtm as a dense matrix
X_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
# count how many times EACH token appears across ALL messages in X_train_dtm
import numpy as np
X_train_counts = np.sum(X_train_dtm.toarray(), axis=0)
X_train_counts

array([ 5, 23,  2, ...,  1,  1,  1])

In [36]:
X_train_counts.shape

(7456,)

In [38]:
# create a DataFrame of tokens with their counts
(pd.DataFrame({'token':X_train_tokens, 'count':X_train_counts})
.sort_values('count', ascending=False))

count      token
6656   1670         to
7420   1660        you
6542   1004        the
929     717        and
3502    683         in
3612    679         is
4238    601         me
3623    568         it
4489    550         my
2821    518        for
7424    508       your
4704    460         of
6539    453       that
1552    443       call
3235    416       have
4743    390         on
4662    361        now
1016    358        are
1574    349        can
6017    344         so
4647    338        not
1522    332        but
4778    306         or
3465    302         if
2995    299        get
1081    298         at
6904    297         ur
7257    293       with
7120    293         we
2290    292         do
...     ...        ...
3157      1        gut
3178      1    haircut
3156      1       gurl
3155      1    guoyang
3154      1      gumby
3153      1     guitar
3151      1     guides
3149      1   guidance
3147      1    guessin
3176      1       hail
3179      1     haiyoh
3216      1    hardest
3199      1     hangin
3215      1     harder
3210      1    happily
3209      1   happiest
3208      1    happier
3202      1  hannaford
3201      1      hanks
3200      1    hanging
3198      1     hanger
3182      1    half8th
3197      1       hang
3196      1  handsomes
3195      1   handsome
3188      1     hamper
3187      1        ham
3184      1      halla
3183      1       hall
7455      1        〨ud

[7456 rows x 2 columns]

## Bonus: Calculating the "spamminess" of each token

In [ ]:
# create separate DataFrames for ham and spam
sms_ham = sms[sms.label==0]
sms_spam = sms[sms.label==1]

In [ ]:
# learn the vocabulary of ALL messages and save it
vect.fit(sms.message)
all_tokens = vect.get_feature_names()

In [ ]:
# create document-term matrices for ham and spam
ham_dtm = vect.transform(sms_ham.message)
spam_dtm = vect.transform(sms_spam.message)

In [ ]:
# count how many times EACH token appears across ALL ham messages
ham_counts = np.sum(ham_dtm.toarray(), axis=0)

In [ ]:
# count how many times EACH token appears across ALL spam messages
spam_counts = np.sum(spam_dtm.toarray(), axis=0)

In [ ]:
# create a DataFrame of tokens with their separate ham and spam counts
token_counts = pd.DataFrame({'token':all_tokens, 'ham':ham_counts, 'spam':spam_counts})

In [ ]:
# add one to ham and spam counts to avoid dividing by zero (in the step that follows)
token_counts['ham'] = token_counts.ham + 1
token_counts['spam'] = token_counts.spam + 1

In [ ]:
# calculate ratio of spam-to-ham for each token
token_counts['spam_ratio'] = token_counts.spam / token_counts.ham
token_counts.sort('spam_ratio')

## Part 5: Building a Naive Bayes model

We will use [Multinomial Naive Bayes](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html):

> The multinomial Naive Bayes classifier is suitable for classification with **discrete features** (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

In [ ]:
# train a Naive Bayes model using X_train_dtm
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

In [ ]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [ ]:
# calculate accuracy of class predictions
from sklearn import metrics
print metrics.accuracy_score(y_test, y_pred_class)

In [ ]:
# confusion matrix
print metrics.confusion_matrix(y_test, y_pred_class)

In [ ]:
# predict (poorly calibrated) probabilities
y_pred_prob = nb.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

In [ ]:
# calculate AUC
print metrics.roc_auc_score(y_test, y_pred_prob)

In [ ]:
# print message text for the false positives
X_test[y_test < y_pred_class]

In [ ]:
# print message text for the false negatives
X_test[y_test > y_pred_class]

In [ ]:
# what do you notice about the false negatives?
X_test[3132]

## Part 6: Comparing Naive Bayes with logistic regression

In [ ]:
# import/instantiate/fit
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_dtm, y_train)

In [ ]:
# class predictions and predicted probabilities
y_pred_class = logreg.predict(X_test_dtm)
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]

In [ ]:
# calculate accuracy and AUC
print metrics.accuracy_score(y_test, y_pred_class)
print metrics.roc_auc_score(y_test, y_pred_prob)